
rssm: {hidden: 200, deter: 200, stoch: 32, discrete: 32, activation: elu, kl_balance: 0.8}
conv_encoder: {activation: elu, cnn_depth: 48, cnn_kernels: [4, 4, 4]}
vector_encoder: {activation: elu, output_dim: 400, layer_sizes: [256], activate_last: True}
fusion_encoder: {activation: elu, output_dim: 200, layer_sizes: [], activate_last: True}

conv_decoder: {activation: elu, cnn_depth: 48, cnn_kernels: [5, 6, 6]}
vector_decoder: {activation: elu, layer_sizes: [256, 256], dist: mse}
reward_decoder: {activation: elu, layer_sizes: [256, 256], output_dim: 1, dist: mse}
discount_decoder: {activation: elu, layer_sizes: [256, 256], output_dim: 1, dist: bernoulli}

image_scale: 1.0
vector_scale: 1000.0
reward_scale: 1000.0
discount_scale: 1.0
beta: 1.0

lr: 1e-4
eps: 1e-5
wd: 1e-6
clip: 100